/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://ihtykzg27naxnl4fztuuhjb56e.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-3s3h77mygzaqfbhbmo2zbrvkp4",
    "aws_cognito_identity_pool_id": "eu-west-1:0a800689-4ed3-446a-8d21-cbf906ac6e15",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_q9FrZDKAE",
    "aws_user_pools_web_client_id": "44tas5kfhonhn9h6h9p01inor0",
    "oauth": {
        "domain": "padelpromanager3ce631af-3ce631af-dev.auth.eu-west-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "PadelProManager://",
        "redirectSignOut": "PadelProManager://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "padelpromanager-storage-0827d0dd202100-dev",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
